# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170527_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(default=0)),
                ('minor', models.IntegerField(default=0)),
                ('rssi', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time_start', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DronePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('time', models.IntegerField(default=0)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Drone')),
            ],
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.AddField(
            model_name='beacon',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Drone'),
        ),
    ]
