# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20170607_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='color',
            field=models.CharField(default=b'red', max_length=20),
        ),
    ]
