# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_drone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
