# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_beacon_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneposition',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
