# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20170611_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='altitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beacon',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beacon',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
