# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20170611_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='altitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
