# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20170611_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='droneposition',
            name='sent',
        ),
    ]
